### ISSUE TITLE
testsuite fails to build with QuickCheck 2.16

### ISSUE THREAD

**Issue by juhp** [well-typed/recover-rtti#43]
```
       Building test suite 'test-recover-rtti' for recover-rtti-0.5.0...                                       03:47:21 [601/909229]
       [ 4 of 14] Compiling Test.RecoverRTTI.Prim                                                                                   
       /home/curators/work/unpack-dir/unpacked/recover-rtti-0.5.0-5f9e048ebb3d9876d68219bee4ead0083a8e3a523775037edcf2679b868e298b/t
ests/Test/RecoverRTTI/Prim.hs:69:33: error: [GHC-87543]
           Ambiguous occurrence ‘Some’.
           It could refer to
              either ‘Debug.RecoverRTTI.Some’,
                     imported from ‘Debug.RecoverRTTI’ at tests/Test/RecoverRTTI/Prim.hs:48:1-24
                     (and originally defined in ‘recover-rtti-0.5.0:Debug.RecoverRTTI.Util’),
                  or ‘Test.QuickCheck.Some’,
                     imported from ‘Test.QuickCheck’ at tests/Test/RecoverRTTI/Prim.hs:50:1-22
                     (and originally defined in ‘Test.QuickCheck.Monoids’).
          |
       69 | arbitraryPrimClassifier :: Gen (Some PrimClassifier)
          |                                 ^^^^
        
       /home/curators/work/unpack-dir/unpacked/recover-rtti-0.5.0-5f9e048ebb3d9876d68219bee4ead0083a8e3a523775037edcf2679b868e298b/t
ests/Test/RecoverRTTI/Prim.hs:73:7: error: [GHC-87543]
           Ambiguous occurrence ‘Some’.
           It could refer to
              either ‘Debug.RecoverRTTI.Some’,
                     imported from ‘Debug.RecoverRTTI’ at tests/Test/RecoverRTTI/Prim.hs:48:1-24
                     (and originally defined in ‘recover-rtti-0.5.0:Debug.RecoverRTTI.Util’),
                  or ‘Test.QuickCheck.Some’,
                     imported from ‘Test.QuickCheck’ at tests/Test/RecoverRTTI/Prim.hs:50:1-22
                     (and originally defined in ‘Test.QuickCheck.Monoids’).
          |
       73 |       Some C_Bool
          |       ^^^^
        
       /home/curators/work/unpack-dir/unpacked/recover-rtti-0.5.0-5f9e048ebb3d9876d68219bee4ead0083a8e3a523775037edcf2679b868e298b/t
ests/Test/RecoverRTTI/Prim.hs:74:7: error: [GHC-87543]
           Ambiguous occurrence ‘Some’.
           It could refer to
              either ‘Debug.RecoverRTTI.Some’,
                     imported from ‘Debug.RecoverRTTI’ at tests/Test/RecoverRTTI/Prim.hs:48:1-24
                     (and originally defined in ‘recover-rtti-0.5.0:Debug.RecoverRTTI.Util’),
                  or ‘Test.QuickCheck.Some’,
                     imported from ‘Test.QuickCheck’ at tests/Test/RecoverRTTI/Prim.hs:50:1-22
                     (and originally defined in ‘Test.QuickCheck.Monoids’).
          |
       74 |     , Some C_Char
:
:
```

**Comment by edsko** [comment]
Thanks for the bug report, I'll take a look.

**Comment by edsko** [comment]
This will be closed by #44.
